# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows: 
  version: 2
  jobs:
    build:
      docker:
        # specify the version you desire here
        - image: circleci/node:10.0.0
        
        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mongo:3.4.4
      steps:
        - checkout
        - run: echo "npm installing"
        - run: npm install
        - run: CI=true npm run build
    test: 
      docker: 
        - image: circleci/node:10.0.0
      steps: 
        - checkout
        - run: echo "testing..."
        - run: npm install 
        - run: npm test
    lint: 
      docker: 
        - image: circleci/node:10.0.0
      steps: 
        - checkout 
        - run: echo: "lint"
        - run: npm install 
        - run: npm run lint
workflows: 
  version: 2
  build_test_and_lint: 
    jobs: 
      - build 
      - test 
      - lint
